name: imaging_course_stardist_day5_2024
channels:
  - conda-forge
dependencies:
  - python==3.9.*
  - conda-forge::ipywidgets==8.0.4
  - pip
  - pip:
    - jupyter==1.0.0
    - stardist==0.8.5
    - matplotlib==3.8.4
    - ome-zarr==0.8.3
    - pandas==2.2.2
    - tensorflow-macos==2.12.0; platform_system == "Darwin"
    - tensorflow==2.12.0; platform_system != "Darwin"
