name: imaging_course_basic_day5_2024
channels:
  - conda-forge
dependencies:
  - python==3.9.*
  - conda-forge::ipywidgets==8.0.4
  - pip
  - pip:
    - dask-image==2023.8.1
    - jupyter==1.0.0
    - matplotlib==3.8.4
    - ome-zarr==0.8.3
    - pandas==2.2.2
