name: imaging_course_conversion_day5_2024
channels:
  - ome
  - conda-forge
  - defaults
dependencies:
  - python == 3.9.*
  - bioformats2raw
  - raw2ometiff
  - pip
  - pip:
    - jupyter==1.0.0
    - napari[all]
    - napari-ome-zarr==0.5.2
