name: imaging_course_day5_2024
channels:
  - conda-forge
dependencies:
  - python==3.9.*
  - conda-forge::ipywidgets==8.0.4
  - pip
  - pip:
    - cellpose==3.0.7
    - matplotlib==3.8.4
    - ome-zarr==0.8.3
    - pandas==2.2.2
    
