name: imaging_course__public_day4_2024
channels:
  - bioconda
  - conda-forge
  - defaults
  - ome
dependencies:
  - python==3.9.*
  - numpy==1.24.3
  - pandas==1.5.3
  - scikit-image==0.19.3
  - ome::zeroc-ice36-python==3.6.5
  - onda-forge::ipywidgets==8.0.4
  - pip
  - pip:
    - intermine==1.13.0
    - omero-py==5.19.1
    - matplotlib==3.8.4
    - scikit-image==0.22.0
